services:
  plugin:
    container_name: ludos-plugin
    build:
      context: ./plugin
      dockerfile: Dockerfile
    volumes:
      - ./plugin:/plugin
      - ./data/plugins:/plugin/build/output

  server:
    container_name: ludos-server
    image: itzg/minecraft-server:stable-java17
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.19"
    volumes:
      - ./data:/data